-- ENITOSIN STORE — Supabase database setup
-- Run this entire script once in Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= 0),
  badge text,
  rating text default '5.0',
  description text default '',
  image text not null,
  stock text default 'In Stock',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  customer jsonb not null,
  items jsonb not null,
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'Processing',
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  joined_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  type text not null,
  message text not null,
  meta jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  notification_email text default '',
  updated_at timestamptz not null default now()
);

insert into public.settings (id, notification_email)
values (1, '')
on conflict (id) do nothing;

create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists activity_logs_timestamp_idx on public.activity_logs (timestamp desc);

-- Keep updated_at current whenever a product is edited.
create or replace function public.set_products_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at
before update on public.products
for each row execute function public.set_products_updated_at();

-- Keep settings.updated_at current.
create or replace function public.set_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists settings_updated_at on public.settings;
create trigger settings_updated_at
before update on public.settings
for each row execute function public.set_settings_updated_at();

-- The browser never talks to these tables directly. The Express backend
-- uses the server-side Supabase secret key. RLS therefore stays enabled.
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.customers enable row level security;
alter table public.activity_logs enable row level security;
alter table public.settings enable row level security;
